# config/packages/doctrine_migrations.yaml
doctrine_migrations:
    # Namespace where your migration classes will be located
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/migrations'

    # Optional settings
    storage:
        table_storage:
            table_name: 'migration_versions' # table to track executed migrations

    all_or_nothing: true                     # if true, all migrations run in one transaction
    check_database_platform: true            # verify platform before executing migration
