lexik_jwt_authentication:
  private_key_path: '%env(resolve:JWT_PRIVATE_KEY_PATH)%'
  public_key_path:  '%env(resolve:JWT_PUBLIC_KEY_PATH)%'
  pass_phrase:      '%env(JWT_PASSPHRASE)%'
  token_ttl:        3600
