[build]
builder = "pack"

[build.env]
COMPOSER_ALLOW_SUPERUSER = "1"

[build.services.web]
buildCommand = "composer install --ignore-platform-reqs"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t public"
